"""Add Google Calendar connection and event ID tables

Revision ID: 0966c1660961
Revises: 3ed27963c12a
Create Date: 2026-08-24 14:39:57.917828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0966c1660961'
down_revision: Union[str, None] = '3ed27963c12a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_calendar_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('scopes', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_calendar_connections_id'), 'google_calendar_connections', ['id'], unique=False)
    op.create_index(op.f('ix_google_calendar_connections_user_id'), 'google_calendar_connections', ['user_id'], unique=True)
    op.add_column('appointments', sa.Column('doctor_google_event_id', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('patient_google_event_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'patient_google_event_id')
    op.drop_column('appointments', 'doctor_google_event_id')
    op.drop_index(op.f('ix_google_calendar_connections_user_id'), table_name='google_calendar_connections')
    op.drop_index(op.f('ix_google_calendar_connections_id'), table_name='google_calendar_connections')
    op.drop_table('google_calendar_connections')
    # ### end Alembic commands ###
