"""Add appointment and slot hold tables

Revision ID: 41b112aea47b
Revises: 26de620fa589
Create Date: 2026-08-23 16:46:15.993491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41b112aea47b'
down_revision: Union[str, None] = '26de620fa589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_profile_id', sa.Integer(), nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('symptoms', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_profile_id'], ['doctor_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_uniq_active_appointment', 'appointments', ['doctor_profile_id', 'appointment_date', 'start_time'], unique=True, postgresql_where=sa.text("status != 'CANCELLED'"))
    op.create_index(op.f('ix_appointments_doctor_profile_id'), 'appointments', ['doctor_profile_id'], unique=False)
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_table('slot_holds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_profile_id', sa.Integer(), nullable=False),
    sa.Column('hold_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_released', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_profile_id'], ['doctor_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slot_holds_doctor_profile_id'), 'slot_holds', ['doctor_profile_id'], unique=False)
    op.create_index(op.f('ix_slot_holds_id'), 'slot_holds', ['id'], unique=False)
    op.create_index(op.f('ix_slot_holds_patient_id'), 'slot_holds', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slot_holds_patient_id'), table_name='slot_holds')
    op.drop_index(op.f('ix_slot_holds_id'), table_name='slot_holds')
    op.drop_index(op.f('ix_slot_holds_doctor_profile_id'), table_name='slot_holds')
    op.drop_table('slot_holds')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_doctor_profile_id'), table_name='appointments')
    op.drop_index('idx_uniq_active_appointment', table_name='appointments', postgresql_where=sa.text("status != 'CANCELLED'"))
    op.drop_table('appointments')
    # ### end Alembic commands ###
