"""Add appointment and slot hold tables

Revision ID: dd30c2b77c3e
Revises: 41b112aea47b
Create Date: 2026-08-23 16:51:50.607633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd30c2b77c3e'
down_revision: Union[str, None] = '41b112aea47b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
