"""Add AI summary and clinical notes columns to appointment

Revision ID: e55bfc438f2c
Revises: dd30c2b77c3e
Create Date: 2026-08-23 21:05:36.149975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e55bfc438f2c'
down_revision: Union[str, None] = 'dd30c2b77c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('clinical_notes', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('prescriptions', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('ai_urgency_level', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('ai_chief_complaint', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('ai_suggested_questions', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('ai_pre_visit_status', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('ai_patient_summary', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('ai_follow_up_instructions', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('ai_post_visit_status', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('ai_model_info', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'ai_model_info')
    op.drop_column('appointments', 'ai_post_visit_status')
    op.drop_column('appointments', 'ai_follow_up_instructions')
    op.drop_column('appointments', 'ai_patient_summary')
    op.drop_column('appointments', 'ai_pre_visit_status')
    op.drop_column('appointments', 'ai_suggested_questions')
    op.drop_column('appointments', 'ai_chief_complaint')
    op.drop_column('appointments', 'ai_urgency_level')
    op.drop_column('appointments', 'prescriptions')
    op.drop_column('appointments', 'clinical_notes')
    # ### end Alembic commands ###
